# Generated by Django 6.0 on 2025-12-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, default='users/6596121.png', null=True, upload_to='users/'),
        ),
    ]
