# Generated by Django 6.0 on 2025-12-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_project', '0002_category_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
