# Generated by Django 6.0 on 2025-12-21 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_project', '0006_comments_active_comments_comment_count_comments_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='news_project.news')),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('news', 'ip_address')},
            },
        ),
    ]
